- require:
    - com.akiban.server.AkServerInterface           # loads the AKSERVER jmx bean
    - com.akiban.server.service.dxl.DXLService           # leads the DDL/DML jmx bean
    - com.akiban.server.service.memcache.MemcacheService # HAPI
    - com.akiban.server.service.network.NetworkService   # MySQL replication
    - com.akiban.server.service.stats.StatisticsService  # Stats gathering
    - com.akiban.server.service.jmx.JmxRegistryService   # Turns on JMX for other services
    - com.akiban.sql.pg.PostgresService                  # Akiban SQL
    - com.akiban.server.service.instrumentation.InstrumentationService
